{
  "Header": {
    "Original": "CVE-2022-0924 (Out-of-bounds Read error in tiffcp in libtiff 4.3.0 allows attackers t ...)",
    "Line": 94247,
    "ID": "CVE-2022-0924",
    "Description": "(Out-of-bounds Read error in tiffcp in libtiff 4.3.0 allows attackers t ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-5108-1}",
      "Line": 94248,
      "Type": "xref",
      "Bugs": [
        "DSA-5108-1"
      ]
    },
    {
      "Original": "- tiff 4.3.0-6",
      "Line": 94249,
      "Type": "package",
      "Package": "tiff",
      "Kind": "fixed",
      "Version": "4.3.0-6"
    },
    {
      "Original": "NOTE: https://gitlab.com/libtiff/libtiff/-/issues/278",
      "Line": 94250,
      "Type": "NOTE",
      "Description": "https://gitlab.com/libtiff/libtiff/-/issues/278"
    },
    {
      "Original": "NOTE: https://gitlab.com/libtiff/libtiff/-/merge_requests/311",
      "Line": 94251,
      "Type": "NOTE",
      "Description": "https://gitlab.com/libtiff/libtiff/-/merge_requests/311"
    },
    {
      "Original": "NOTE: https://gitlab.com/libtiff/libtiff/-/commit/88d79a45a31c74cba98c697892fed5f7db8b963a",
      "Line": 94252,
      "Type": "NOTE",
      "Description": "https://gitlab.com/libtiff/libtiff/-/commit/88d79a45a31c74cba98c697892fed5f7db8b963a"
    }
  ]
}