{
  "Header": {
    "Original": "CVE-2022-43681 (An out-of-bounds read exists in the BGP daemon of FRRouting FRR throug ...)",
    "Line": 46927,
    "ID": "CVE-2022-43681",
    "Description": "(An out-of-bounds read exists in the BGP daemon of FRRouting FRR throug ...)"
  },
  "Annotations": [
    {
      "Original": "- frr \u003cunfixed\u003e (bug #1035829)",
      "Line": 46928,
      "Type": "package",
      "Package": "frr",
      "Kind": "unfixed",
      "BugNo": 1035829
    },
    {
      "Original": "NOTE: https://github.com/FRRouting/frr/issues/13427",
      "Line": 46929,
      "Type": "NOTE",
      "Description": "https://github.com/FRRouting/frr/issues/13427"
    },
    {
      "Original": "NOTE: https://github.com/FRRouting/frr/issues/13480",
      "Line": 46930,
      "Type": "NOTE",
      "Description": "https://github.com/FRRouting/frr/issues/13480"
    },
    {
      "Original": "NOTE: Fixes for CVE-2022-43681/CVE-2022-40318/CVE-2022-40302:",
      "Line": 46931,
      "Type": "NOTE",
      "Description": "Fixes for CVE-2022-43681/CVE-2022-40318/CVE-2022-40302:"
    },
    {
      "Original": "NOTE: https://github.com/FRRouting/frr/commit/1117baca3c592877a4d8a13ed6a1d9bd83977487 (base_8.4)",
      "Line": 46932,
      "Type": "NOTE",
      "Description": "https://github.com/FRRouting/frr/commit/1117baca3c592877a4d8a13ed6a1d9bd83977487 (base_8.4)"
    },
    {
      "Original": "NOTE: https://github.com/FRRouting/frr/commit/3e46b43e3788f0f87bae56a86b54d412b4710286 (base_8.4)",
      "Line": 46933,
      "Type": "NOTE",
      "Description": "https://github.com/FRRouting/frr/commit/3e46b43e3788f0f87bae56a86b54d412b4710286 (base_8.4)"
    },
    {
      "Original": "NOTE: https://github.com/FRRouting/frr/commit/766eec1b7accffe2c04a5c9ebb14e9f487bb9f78 (base_8.5)",
      "Line": 46934,
      "Type": "NOTE",
      "Description": "https://github.com/FRRouting/frr/commit/766eec1b7accffe2c04a5c9ebb14e9f487bb9f78 (base_8.5)"
    }
  ]
}